User.create!(name:  "Zack Falgout",
             email: "ZFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Lauren Falgout",
             email: "LFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Paul Falgout",
             email: "PFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Teenie Falgout",
             email: "TFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Emma Falgout",
             email: "EFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Thomas Falgout",
             email: "TFalgout@lsu.edu",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

Match.create!(player1: 1,
              user_id: 1,
              player2: "2",
              player3: "",
              player4: "",
              game_type: "Singles",
              open: 0,
              zip: 77706,
              p2Active: 1,
              p3Active: 1,
              p4Active: 1,
              player2Accept: 1,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: Date.yesterday,
              location: "Beaumont")

Match.create!(player1: 1,
              user_id: 1,
              player2: "2",
              player3: "3",
              player4: "4",
              game_type: "Doubles",
              open: 0,
              zip: 77706,
              p2Active: 1,
              p3Active: 1,
              p4Active: 1,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: 3.days.ago,
              location: "Beaumont")

Match.create!(player1: 1,
              user_id: 1,
              player2: "2",
              player3: "3",
              player4: "4",
              game_type: "Doubles",
              open: 0,
              zip: 77706,
              p2Active: 0,
              p3Active: 0,
              p4Active: 0,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: 3.days.from_now,
              location: "Beaumont")