User.create!(name:  "Zack Falgout",
             email: "ZFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Lauren Falgout",
             email: "LFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Paul Falgout",
             email: "PFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Teenie Falgout",
             email: "TFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Emma Falgout",
             email: "EFalgout@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Thomas Falgout",
             email: "TFalgout@lsu.edu",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

User.create!(name:  "Tester",
             email: "Tester@gmail.com",
             zip: "77706",
             password:              "CS7000",
             password_confirmation: "CS7000",
             activated: true,
             activated_at: Time.zone.now)

99.times do |n|
  name  = Faker::Name.name
  email = "User#{n+1}@gmails.com"
  password = "CS7000"
  User.create!(name:  name,
               email: email,
               zip: "77706",
               activated: true,
               activated_at: Time.zone.now,
               password:              password,
               password_confirmation: password)
end

  Match.create!(player1: 1,
                user_id: 1,
                player2: "2",
                player3: "",
                player4: "",
                game_type: "Singles",
                open: 0,
                zip: 77706,
                p2Active: 1,
                p3Active: 1,
                p4Active: 1,
                player2Accept: 1,
                player3Accept: nil,
                player4Accept: nil,
                scoreValid: 0,
                validated: 3,
                time: Date.yesterday,
                location: "Beaumont")

99.times do |n|
  Match.create!(player1: 3,
                user_id: 3,
                player2: "4",
                player3: "",
                player4: "",
                game_type: "Singles",
                open: 0,
                zip: 77706,
                p2Active: 1,
                p3Active: 1,
                p4Active: 1,
                player2Accept: 1,
                player3Accept: nil,
                player4Accept: nil,
                scoreValid: 0,
                validated: 3,
                time: Date.yesterday,
                location: "Beaumont")
end

Match.create!(player1: 1,
              user_id: 1,
              player2: "2",
              player3: "3",
              player4: "4",
              game_type: "Doubles",
              open: 0,
              zip: 77706,
              p2Active: 1,
              p3Active: 1,
              p4Active: 1,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: 3.days.ago,
              location: "Beaumont")

Match.create!(player1: 1,
              user_id: 1,
              player2: "2",
              player3: "3",
              player4: "4",
              game_type: "Doubles",
              open: 0,
              zip: 77706,
              p2Active: 0,
              p3Active: 0,
              p4Active: 0,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: 3.days.from_now,
              location: "Beaumont")

Match.create!(player1: 2,
              user_id: 2,
              player2: "1",
              player3: "3",
              player4: "4",
              game_type: "Doubles",
              open: 0,
              zip: 77706,
              p2Active: 0,
              p3Active: 0,
              p4Active: 0,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: 3.days.from_now,
              location: "Beaumont")

Match.create!(player1: 3,
              user_id: 3,
              game_type: "Doubles",
              open: 1,
              zip: 77706,
              p2Active: 0,
              p3Active: 0,
              p4Active: 0,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: 4.days.from_now,
              location: "Beaumont")

Match.create!(player1: 1,
              user_id: 1,
              player2: "Player 2",
              player3: "",
              player4: "",
              game_type: "Singles",
              open: 1,
              zip: 77706,
              p2Active: 0,
              p3Active: 0,
              p4Active: 0,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: 5.days.from_now,
              location: "Beaumont")

99.times do |n|
  Match.create!(player1: 1,
                user_id: 1,
                game_type: "Doubles",
                open: 1,
                zip: 77845,
                p2Active: 0,
                p3Active: 0,
                p4Active: 0,
                player2Accept: nil,
                player3Accept: nil,
                player4Accept: nil,
                scoreValid: 0,
                validated: 3,
                time: 1.year.from_now,
                location: "Beaumont")
end

Match.create!(player1: 2,
              user_id: 2,
              player2: "1",
              player3: "",
              player4: "",
              game_type: "Singles",
              open: 0,
              zip: 77706,
              p2Active: 0,
              p3Active: 1,
              p4Active: 1,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: Date.tomorrow,
              location: "Beaumont")

Match.create!(player1: 1,
              user_id: 1,
              player2: "7",
              player3: "",
              player4: "",
              game_type: "Singles",
              open: 0,
              zip: 77845,
              p2Active: 0,
              p3Active: 1,
              p4Active: 1,
              player2Accept: nil,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: 4.days.from_now,
              location: "Beaumont")

Match.create!(player1: 7,
              user_id: 7,
              player2: "2",
              player3: "",
              player4: "",
              game_type: "Singles",
              open: 0,
              zip: 77706,
              p2Active: 1,
              p3Active: 1,
              p4Active: 1,
              player2Accept: 1,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 0,
              validated: 3,
              time: Date.yesterday,
              location: "Beaumont")

Match.create!(player1: 1,
              user_id: 1,
              player2: "7",
              player3: "",
              player4: "",
              game_type: "Singles",
              open: 0,
              zip: 77706,
              p2Active: 1,
              p3Active: 1,
              p4Active: 1,
              player2Accept: 1,
              player3Accept: nil,
              player4Accept: nil,
              scoreValid: 1,
              winner: "Tester",
              validated: 1,
              time: Date.yesterday,
              location: "Beaumont",
              validator1: 7,
              score: "6-4, 4-6, 6-4")